nexuswave/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.urls import include, path

from . import views

app_name = "website"

urlpatterns = [ 
    path("", views.HomeView.as_view(), name="website_index"),
    path("erp-solutions/", views.ERPView.as_view(), name="website_erp"),
    path("about/", views.AboutView.as_view(), name="website_about"),
    path("contact/", views.ContactView.as_view(), name="website_contact"),
    path("services/", views.ServicesView.as_view(), name="website_service"),
    path("social-media-management/", views.SmmView.as_view(), name="website_social"),
    path("website-dev/", views.WebsiteDevView.as_view(), name="website_web_development"),
    path("website-hosting/", views.WebHostingView.as_view(), name="website_hosting"),
    path("graphic-design/", views.GraphicDesignView.as_view(), name="website_graphic_design"),
    path("request-service/", views.ServicerCreateView.as_view(), name="contact-service"),
    path("request-service/<slug:category>/", views.ServicerCreateView.as_view(), name="request-service"),
    path("thanks/", views.ContactServiceDetails.as_view(), name="contact-thanks"),
    path("thanks/<slug:slug>/", views.RequestServiceDetails.as_view(), name="request-service-detail"),
    path("digital-marketing/", views.DmView.as_view(), name="website_digital_marketing"),
    path("company-privacy/", views.CompanyPrivacy.as_view(), name="website_privacy"),
    path("company-rules/", views.CompanyRules.as_view(), name="website_rules"),
]

website/models.py
import uuid

from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _


class ServiceCategory(models.Model):
    name = models.CharField(max_length=200)
    code = models.SlugField(allow_unicode=False)
    active = models.BooleanField(default=True, verbose_name=_("Active"))

    def __str__(self):
        return self.name

    def clean(self):
        super().clean()
        if self.code and ServiceCategory.objects.filter(code=self.code).exclude(pk=self.pk).exists():
            raise ValidationError({"code": _("Service Category Code Already Exists, please use another code.")})


class Service(models.Model):
    name = models.CharField(max_length=200)
    code = models.SlugField(allow_unicode=False, default=uuid.uuid4)
    price = models.FloatField(default=0)
    note = models.TextField(_("Description"), default="", blank=True)
    active = models.BooleanField(default=True, verbose_name=_("Active"))
    category = models.ForeignKey(ServiceCategory, on_delete=models.PROTECT, null=True)
    one_time_service = models.BooleanField(default=True)
    subscrition = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class CustomerRequest(models.Model):
    class RequestStatus(models.TextChoices):
        WAITING = "waiting", _("Waiting")
        REVIEW = "review", _("Review")
        Done = "done", _("Done")
        CANCEL = "cancel", _("Cancel")

    class RequestType(models.TextChoices):
        ONETIME = "one_time", _("طلب خدمة لمرة واحدة")
        SUBSCRIPTION = "subscrition", _("اشتراك  سنوي")

    name = models.CharField(max_length=200, verbose_name="اسمك ", help_text="ُاكتب اسمك او عنوان الطلب")
    email = models.EmailField(max_length=254, verbose_name="ايميلك ", help_text="ُاكتب ايميلك ليتم التواصل معك")
    phone = models.CharField(max_length=20, verbose_name="رقم الهاتف ", help_text="")
    company = models.CharField(max_length=300, verbose_name="اسم المؤسسة /الشركة", help_text="")
    category = models.ForeignKey(ServiceCategory, on_delete=models.PROTECT, null=True, blank=True)
    services = models.ManyToManyField(Service)
    slug = models.SlugField(unique=True, db_index=True, default=uuid.uuid4, editable=False, blank=True)
    ip_address = models.GenericIPAddressField("IP", blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    state = models.CharField(
        verbose_name=_("Status"),
        max_length=10,
        choices=RequestStatus.choices,
        default=RequestStatus.WAITING,
    )
    active = models.BooleanField(default=True, verbose_name=_("Active"))

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # if not self.slug :
        #     self.slug = self.unique_slug_generator()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("website:request-service-detail", kwargs={"slug": self.slug})

    def unique_slug_generator(self):
        constant_slug = slugify(self.phone)
        slug = constant_slug
        num = 0
        Klass = self.__class__
        while Klass.objects.filter(slug=slug).exists():
            num += 1
            slug = "{slug}-{num}".format(slug=constant_slug, num=num)
        return slug

website/forms.py
 

from django import forms

from website.models import CustomerRequest, Service

class RequestServiceForm(forms.ModelForm):
    """Form definition for PaymentVoucher."""

     
    services = forms.ModelMultipleChoiceField(
        queryset=Service.objects.filter(active=True),required=False,
        widget=forms.CheckboxSelectMultiple(),
    )

    class Meta:
        """Meta definition for PaymentVoucher."""

        model = CustomerRequest
        exclude = ("state","active",)

website/views.py
from django.apps import apps
from django.contrib.auth import get_user_model
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.http import HttpResponse
from django.shortcuts import render
from django.template import Context
from django.template.loader import get_template
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django_mail_admin import mail, models
from pyexpat.errors import messages

from website.forms import RequestServiceForm
from website.models import CustomerRequest


class HomeView(TemplateView):
    template_name = "website/coretech/index.html"


class ERPView(TemplateView):
    template_name = "website/coretech/erp_solutions.html"


class AboutView(TemplateView):
    template_name = "website/coretech/about.html"


class ContactView(TemplateView):
    template_name = "website/coretech/contact.html"


class ServicesView(TemplateView):
    template_name = "website/coretech/services.html"

class SmmView(TemplateView):
    template_name = "website/coretech/social_media_management.html"

class WebsiteDevView(TemplateView):
    template_name = "website/coretech/website_development.html"

class WebHostingView(TemplateView):
    template_name = "website/coretech/website_hosting.html"


class GraphicDesignView(TemplateView):
    template_name = "website/coretech/graphic_design.html"

class DmView(TemplateView):
    template_name = "website/coretech/digital_marketing.html"

class CompanyPrivacy(TemplateView):
    template_name = "website/coretech/privacy.html"

class CompanyRules(TemplateView):
    template_name = "website/coretech/rules.html"


class ContactServiceDetails(TemplateView):
    template_name = "website/coretech/thanks.html"


from django.utils import timezone
from django.views.generic.detail import DetailView


def get_client_ip_address(request):
    req_headers = request.META
    x_forwarded_for_value = req_headers.get("HTTP_X_FORWARDED_FOR")
    if x_forwarded_for_value:
        ip_addr = x_forwarded_for_value.split(",")[-1].strip()
    else:
        ip_addr = req_headers.get("REMOTE_ADDR")
    return ip_addr


class RequestServiceDetails(DetailView):
    template_name = "website/coretech/thanks.html"
    model = CustomerRequest


class ServicerCreateView(CreateView):
    # model = ContactServiceEntry
    form_class  = RequestServiceForm
    # fields = "__all__"
    template_name = 'website/coretech/contact_services.html'
    
    # success_url = '/thanks/'
    
    def _get_default_services(self):
        category_code = self.kwargs.get("category",None)
        services = apps.get_model("website.Service").objects.filter(active=True)
        if category_code:
            category = apps.get_model("website.ServiceCategory").objects.filter(code = category_code).first()
            if category:
                services = services.filter(category = category)
        return services

    
    def get_form(self, form_class = None):
        form = super().get_form(form_class)
        if form.fields and form.fields.get("services",None):
            form.fields['services'].queryset = self._get_default_services()
        return form
    
    def _send_email(self,form):
        try:
            obj = form.instance
            services = form.cleaned_data.get("services",[]) or []
            subject, from_email, to = f"You have a new request from {obj.company}", "dev@core-tech.sa", "info@core-tech.sa"
            plain_tmpl = get_template('website/email/email.txt')
            html_tmpl     = get_template('website/email/email.html')
            ctx = { 'username': "CoreTech" ,"obj":obj,"services":services}
            text_content = plain_tmpl.render(ctx)
            html_content = html_tmpl.render(ctx)
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            msg.send(fail_silently=True)
            # print(msg.send())

            # msg = EmailMessage(subject, html_content, from_email, [to])
            # msg.content_subtype = "html"  # Main content is now text/html
            # msg.send()
        except Exception as ex:
            print(ex)

    def form_valid(self, form):
        form.instance.ip_address = get_client_ip_address(self.request)
        result = super().form_valid(form)
        self._send_email(form)
        return result
    

website/templates/website/coretech/_footer.html
<footer class="footer-wrapper footer-layout1">
    <div class="widget-area">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-md-6 col-xl-4">
                    <div class="widget footer-widget">
                        <h3 class="widget_title">عن الموجة التالية</h3>
                        <div class="as-widget-about">
                            <p class="about-text"> الموجة المركزية تعمل لتقدم حلول مصممة خصيصاً لتلبية احتياجات الشركات والمؤسسات والقطاعات التجارية والخدمية بأفضل الحلول التقنية الحديثة والخدمات الرقمية بأعلى مستويات الأداء والفعالية لعملائها

                            </p>
                            <div class="social-box mb-30">
                                <h6 class="social-title" style="margin-left: 10px"> تابعنا :</h6>

                                <div class="icon-group ">
                                    <a target="_blank" href="#"><i class="fab fa-tiktok"></i></a>
                                    <a target="_blank" href="#"><i class="fab fa-instagram"></i></a>
                                    <a target="_blank" href="#"><i class="fab fa-twitter"></i></a>
                                    <a target="_blank" href="#"><i class="fab fa-facebook-f"></i></a>
                                </div>
                            </div>
                            <form class="newsletter-form">
                                <input class="form-control" type="email" placeholder="ادخل ايميلك" required="">
                                <button type="submit" class="as-btn style4">اشترك معنا</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-xl-auto">
                    <div class="widget widget_nav_menu footer-widget">
                        <h3 class="widget_title">روابط سريعه</h3>
                        <div class="menu-all-pages-container">
                            <ul class="menu">
                                <li><a href="{% url 'website:website_about' %}">من نحن</a></li>
                                <li><a href="{% url 'website:website_erp' %}">منصة تام التقنية</a></li>

                                <li><a href="{% url 'website:website_contact' %}"> تواصل معنا</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-xl-auto">
                    <div class="widget widget_nav_menu footer-widget">
                        <h3 class="widget_title">خدماتنا</h3>
                        <div class="menu-all-pages-container">
                            <ul class="menu">
                                <li>
                                    <a href="{% url 'website:website_erp' %}">منصة تام التقنية</a>
                                   </li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="copyright-wrap">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-lg-3">
                    <p class="copyright-text"> 2024
                        الحقوق محفوظة لدى
                        <i class="fal fa-copyright"></i> Nexus Wave
                    </p>
                </div>
                <div class="col-lg-6 text-end d-none d-lg-block">
                    <div class="footer-links">

                        <ul>
                            <li><a href="{% url 'website:website_privacy' %}">سياسة الخصوصية</a></li>
                            <li><a href="{% url 'website:website_rules' %}">الشروط والاحكام  </a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <span class="span">
                        صنع بحب <i class="fa fa-heart pulse"></i> في <a href="#" target="_blank">السعودية</a>
                    </span>
                </div>
            </div>

        </div>
    </div>
</footer>

website/templates/website/coretech/_header.html
{% load static %}
<!--==============================
        Mobile Menu
    ============================== -->
<div class="as-menu-wrapper">
 <div class="as-menu-area text-center">
  <button class="as-menu-toggle">
   <i class="fal fa-times"></i>
  </button>
  <div class="mobile-logo">
   <a href="{% url 'website:website_index' %}">
    <img src="{% static 'website/coretech/assets/img/logo.png' %}" alt="core-tech">
   </a>
  </div>
  <div class="as-mobile-menu">
   <ul>
    <li>
     <a href="{% url 'website:website_index' %}">الصفحة الرئيسية</a>
    </li>
    <li>
     <a href="{% url 'website:website_erp' %}">منصة تام التقنية</a>
    </li>
    <li>
     <a href="{% url 'website:website_about' %}">من نحن</a>
    </li>
    <li>
     <a href="{% url 'website:website_contact' %}">تواصل معنا</a>
    </li>
{#       <li>#}
{#     <a href="https://demo.mawja.io" class="as-btn text-white" data-bs-toggle="modal" >الدخول للنظام </a>#}
{#    </li>#}
   </ul>
      <div class="px-3">
      <a href="#" class="as-btn text-white px-50" data-bs-toggle="modal" data-bs-target="#staticBackdrop">الدخول للنظام </a>
      </div>
  </div>
 </div>
</div>
<!--==============================
        Header Area
    ==============================-->
<header class="as-header header-layout2">
 <div class="header-top">
  <div class="container">
   <div class="row justify-content-center justify-content-lg-between align-items-center gy-2">
    <div class="col-auto d-none d-lg-block">
     <p class="header-notice">
      أفضل الحلول المصممة لعملك. <strong><a href="{% url 'website:website_contact' %}">تواصل معنا</a></strong>
     </p>
    </div>
    <div class="col-auto">
     <div class="header-social">
      <span class="social-title ">تابعنا :</span>
      <a target="_blank" href="#"><i class="fab fa-tiktok"></i></a>
      <a target="_blank" href="#"><i class="fab fa-instagram"></i></a>
      <a target="_blank" href="#"><i class="fab fa-twitter"></i></a>
      <a target="_blank" href="#"><i class="fab fa-facebook-f"></i></a>
     </div>
    </div>
   </div>
  </div>
 </div>
 <div class="sticky-wrapper">
  <div class="sticky-active">
   <!-- Main Menu Area -->
   <div class="container">
    <div class="menu-area">
     <div class="shape_before">
      <img src="{% static 'website/coretech/assets/img/shape/header_shape_1.svg' %}"
           alt="shape">
     </div>
     <div class="shape_after">
      <img src="{% static 'website/coretech/assets/img/shape/header_shape_2.svg' %}"
           alt="shape">
     </div>
     <div class="row align-items-center justify-content-between">
      <div class="col-auto">
       <div class="header-logo">
        <a href="{% url 'website:website_index' %}">
         <img src="{% static 'website/coretech/assets/img/logo.png' %}" alt="core-tech">
        </a>
       </div>
      </div>
      <div class="col-auto">
       <nav class="main-menu d-none d-lg-inline-block">
        <ul>
         <li>
          <a href="{% url 'website:website_index' %}">الصفحة الرئيسية</a>
         </li>
         <li>
          <a href="{% url 'website:website_erp' %}">منصة تام التقنية</a>
         </li>
         <li>
          <a href="{% url 'website:website_about' %}">من نحن</a>
         </li>
         <li>
          <a href="{% url 'website:website_contact' %}">تواصل معنا</a>
         </li>
        </ul>
       </nav>
       <button type="button" class="as-menu-toggle d-inline-block d-lg-none">
        <i class="far fa-bars"></i>
       </button>
      </div>
      <div class="col-auto d-none d-xl-block">
	     <div class="col-lg-auto mt-35 mt-lg-0">
                                      <div class="text-center">
                                      <a href="#" class="as-btn text-white px-50" data-bs-toggle="modal" data-bs-target="#staticBackdrop">الدخول للنظام </a>
                                      </div>
                                      </div>
	  </div>
     </div>
    </div>
   </div>
  </div>
 </div>
</header>

website/templates/website/coretech/about.html
{% extends 'website/coretech/_base.html' %}
{% block title %} من نحن{% endblock title %}
{% load static %}
{% block content %}
    <!--==============================
    Breadcumb
============================== -->
    <div class="breadcumb-wrapper background-about"
         style="background: linear-gradient(to top, #3c3369ba, #4c4779cc), url({% static 'website/coretech/assets/img/breadcum/istockphoto-1221653457-170667a.jpg' %}) no-repeat;">
        <div class="container">
            <div class="breadcumb-content">
                <h1 class="breadcumb-title"> من نحن
                </h1>
                <ul class="breadcumb-menu">
                    <li><a href="{% url 'website:website_index' %}">الصفحة الرئيسية</a></li>
                    <li> من نحن
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!--======== / Hero Section ========-->
    <!--==============================
    About Area  
    ==============================-->
    <div class="overflow-hidden space">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-7 pe-xxl-5">
                    <div class="img-box3">
                        <div class="img1">
                            <img src="{% static 'website/coretech/assets/img/normal/about_2_1.jpg' %}" alt="About">
                        </div>
                        <div class="shape1">
                            <img src="{% static 'website/coretech/assets/img/shape/Asset 5-8.png' %}" alt="shape">
                        </div>
                        <div class="about-counter1">
                        </div>
                    </div>
                </div>
                <div class="col-xl-5">
                    <div class="title-area  mb-30">

                        <h2 class="sec-title text-start">
                            من نحن

                        </h2>
                    </div>
                    <p class="mt-n2 mb-4">
                        الموجة المركزية نطمح لنكون احدى اهم الشركات الرائدة في مجال تطوير البرمجيات والخدمات السحابية
                        المدعومة تقنيات وخدمات الذكاء الاصطناعي لتقدم حلول مصممة خصيصاً لتلبية احتياجات الشركات
                        والمؤسسات والقطاعات التجارية والخدمية بأفضل الحلول التقنية الحديثة والخدمات الرقمية بأعلى
                        مستويات الأداء والفعالية لعملائها. نحن مجموعة من خبراء التقنية يجمعهم هدف ورؤية مشتركة لتطوير
                        الخدمات الحاسوبية بالذكاء الاصطناعي تحت اطر واسس تعمل على تلبية احتياجات رواد الاعمال والقطاع
                        الخاص والدفع بعجلة التطوير الرقمي نحو تحقيق رؤية 2030.
                    </p>
                    <div class="btn-wrap mt-30">

                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="space">
        <div class="container">
            <div class="row justify-content-between">

                <div class="col-xl-12 mt-5 mt-xl-0">
                    <div class="custom-box2">
                        <div class="tab-menu3 filter-menu-active">
                            <button data-filter=".cat1" class="active" type="button">رؤيتنا</button>
                            <button data-filter=".cat2" type="button">مهمتنا</button>
                            <button data-filter=".cat3" type="button">اهدافنا</button>
                        </div>
                        <div class="filter-active-cat1">
                            <div class="filter-item w-100 cat1">

                                <div class="mission-list">
                                    <div class="rounded-10">
                                        <img src="{% static 'website/coretech/assets/img/normal/mission_1.jpg' %}"
                                             alt="Mission">
                                    </div>
                                    <div class="ticklist">
                                        <p class="mb-30">
                                            تطمح الموجة المركزية لتكون من بين أفضل شركات التقنية ومزودي الخدمات الرقمية
                                            في السعودية ودول الخليج و التي تقدم أوسع نطاق من الخدمات المعتمدة والرائدة
                                            وتساهم في تحقيق رؤية ٢٠٣٠ والوصول لأعلى المستويات في الانظمة الرقمية الحديث
                                            المدعمة بالذكاء الاصطناعي.
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="filter-item w-100 cat2">
                                <div class="mission-list">
                                    <div class="rounded-10">
                                        <img src="{% static 'website/coretech/assets/img/normal/mission_2.jpg' %}"
                                             alt="Mission">
                                    </div>
                                    <div class="ticklist">
                                        <p>
                                            في الموجة المركزية ندعم عملائنا في منطقة الخليج العربي لتحقيق الانتشار عبر
                                            الخدمات السحابية والبرمجيات المدعمة بتقنيات الذكاء الاصطناعي المختلفة وبناء
                                            مجتمع متكامل لها مما يساهم في رفع كفاءة الإدارة لدى العملاء وعبر تقديم
                                            مجموعة كاملة من الحلول تبدء بدء بأنظمة الإدارة المتكاملة مرورا بالتصميم
                                            والتسويق الالكتروني بكافة أركانه وانتهاء بالتقارير والمتابعات و توظيف خدمات
                                            الذكاء الاصطناعي مما يعود على تحقيق الأهداف الربحية والإدارية للمؤسسات
                                            والشركات.
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="filter-item w-100 cat3">
                                <div class="mission-list">
                                    <div class="rounded-10">
                                        <img src="{% static 'website/coretech/assets/img/normal/mission_3.jpg' %}"
                                             alt="Mission">
                                    </div>
                                    <div class="ticklist">
                                        <ul>
                                            <li>
                                                توفير أنظمة سحابية مرنة وسهلة الاستخدام مدعمة بتقنية الذكاء الاصطناعي
                                                تناسب كافة الاحتياجات المحاسبية والإدارية.
                                            </li>
                                            <li>
                                                تلبية كافة احتياجات العملاء الرقمية وخلق تجربة فريدة تؤام كل عميل.
                                            </li>
                                            <li>
                                                انعكاس جودة خدماتنا على تطور ونجاح العملاء في سوق العمل.
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

website/templates/website/coretech/contact.html
{% extends 'website/coretech/_base.html' %}
{% block title %} تواصل معنا {% endblock title %}

{% load static %}
{% block content %}    <!--==============================
    Breadcumb
============================== -->
    <div class="breadcumb-wrapper " style="background: linear-gradient(to top, #3c3369ba, #4c4779cc), url({%static 'website/coretech/assets/img/breadcum/istockphoto-1311934969-612x612.jpg'%}) no-repeat;">
        <div class="container">
            <div class="breadcumb-content">
                <h1 class="breadcumb-title">اتصل بنا
                </h1>
                <ul class="breadcumb-menu">
                    <li><a href="{% url 'website:website_index' %}">الصفحة الرئيسية</a></li>
                    <li>اتصل بنا
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!--==============================
Contact Area  
==============================-->
    <div class="space">
        <div class="container">
            <div class="row gy-40">
                <div class="col-xl-5">
                    <div class="contact-info-wrap">
                        <h2 class="fs-40 border-title">معلومات الاتصال</h2>
                        <div class="contact-info">
                            <h4 class="contact-info_title">رقم هاتف:</h4>
                            <div class="contact-info_icon">
                                <i class="fal fa-phone"></i>
                            </div>
                            <div class="media-body">
                                <span class="contact-info_text" dir="ltr">
                                    <a href="tel:++9660534862079">+9660534862079</a>
                                  
                                </span>
                            </div>
                        </div>
                        <div class="contact-info">
                            <h4 class="contact-info_title">عنوان البريد:</h4>
                            <div class="contact-info_icon">
                                <i class="fal fa-envelope"></i>
                            </div>
                            <div class="media-body">
                                <span class="contact-info_text">
                                    <a href="mailto:z.alhosamyfx@gmail.com">z.alhosamyfx@gmail.com</a>
                                </span>
                            </div>
                        </div>
                        <div class="contact-info">
                            <h4 class="contact-info_title">عنوان المكتب:</h4>
                            <div class="contact-info_icon">
                                <i class="fal fa-location-dot"></i>
                            </div>
                            <div class="media-body">
                                <span class="contact-info_text">السعودية</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-7">
                    <div class="contact-map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4740308.26398404!2d46.5097499164811!3d23.897729471020345!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e2f03890d489399%3A0xba974d1c98e79fd5!2z2KfZhNix2YrYp9i2INin2YTYs9i52YjYr9mK2Kk!5e0!3m2!1sar!2s!4v1674410109547!5m2!1sar!2s"  style="border:0;width: 100%;height: 519px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--==============================
Contact Area  
==============================-->
    <section class="space-bottom overflow-hidden">
        <div class="container">
            <div class="row gy-40 align-items-end">
                <div class="col-xl-8">
                    <h3 class="fs-40 mb-2 mt-n2">اترك لنا ملاحظة</h3>
                    <form action="mail.php" method="POST" class="quote-form ajax-contact">
                        <div class="row">
                            <div class="form-group col-md-6">
                                <input type="text" class="form-control" name="name" id="name" placeholder="اسمك">
                                <i class="fal fa-user"></i>
                            </div>
                            <div class="form-group  col-md-6">
                                <input type="email" class="form-control" name="email" id="email" placeholder="عنوان البريد الإلكتروني">
                                <i class="fal fa-envelope"></i>
                            </div>
                            <div class="form-group  col-md-12">
                                <input type="tel"  class="form-control" name="number" id="number" placeholder="رقم الهاتف">
                                <i class="fal fa-phone"></i>
                            </div>
                           
                            <div class="form-group col-12">
                                <textarea name="message" id="message" cols="30" rows="3" class="form-control" placeholder="رسالتك"></textarea>
                                <i class="fal fa-comment"></i>
                            </div>
                            <div class="form-btn col-12">
                                <button class="as-btn">أرسل رسالة</button>
                            </div>
                        </div>
                        <p class="form-messages mb-0 mt-3"></p>
                    </form>
                </div>
                <div class="col-xl-4">
                    <div class="contact-img">
                        <img src="{%static 'website/coretech/assets/img/normal/contact_1.png'%}" alt="vector">
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock content %}